### ISSUE TITLE
Minor Graphical Issue with "Military Calculator" Button

### ISSUE THREAD

**Issue by ArcherSagittarius** [alexbance/rp-centre#19]
The "Military Calculator" button tries to finish it's text underneath the button.
![image](https://cloud.githubusercontent.com/assets/20400277/26662854/18228b12-4644-11e7-89b4-7f8960103f18.png)

**Comment by alexbance** [comment]
Thanks for this, should be fixed when #21 is merged.

**Comment by alexbance** [comment]
@ArcherSagittarius this should be resolved, please re-open if it isn't
