### ISSUE TITLE
Redirect to https

### ISSUE THREAD

**Issue by alexbance** [alexbance/rp-centre#23]
Currently it gives you a 404 if hit http://rpcentre.bancey.xyz

**Comment by alexbance** [comment]
Looks like the following iptables rule fixed this `sudo iptables -t nat -A OUTPUT -o lo -p tcp --dport 80 -j REDIRECT --to-port 8080`

**Comment by alexbance** [comment]
Added `iptables-persistent` package to the server to make sure the above rule is reapplied on reboot

**Comment by alexbance** [comment]
This does fix it for mobile devices

**Comment by alexbance** [comment]
Should be fixed by #48

**Comment by ModzOnYT** [comment]
For me, it is fixed (Google Chrome Android client). Unsure about others but I assume it's fixed for them as well

**Comment by alexbance** [comment]
Cool thanks @ModzOnYT I looks like its been fixed from my testing but I'll leave it open for a bit to make sure it doesn't resurface.
