### ISSUE TITLE
Military Calculator doesn't calculate budget

### ISSUE THREAD

**Issue by ModzOnYT** [alexbance/rp-centre#25]
Full log of browser console:
https://pastebin.com/raw/Bpkknbg4
Firefox version: 48.0.2
Also tried on Edge/Chrome

**Comment by alexbance** [comment]
I'm unable to reproduce this error with my own account, could you provide me with the name of the nation you used?

**Comment by ModzOnYT** [comment]
Retinentia is the name of the nation.

**Comment by alexbance** [comment]
Looks like we'll need to re-work the formula, to handle negative values.

**Comment by alexbance** [comment]
Will be fixed in the next release

**Comment by alexbance** [comment]
#43
