### ISSUE TITLE
No Formatting Method

### ISSUE THREAD

**Issue by josephward** [alexbance/rp-centre#26]
Original Formatting 
![image](https://user-images.githubusercontent.com/20400277/26913049-ad561dde-4bd5-11e7-9b26-dd563bbe1fa4.png)

Formatting on Post
![image](https://user-images.githubusercontent.com/20400277/26913028-8152f892-4bd5-11e7-9875-231b57acfba5.png)

I pasted in my roleplay as it is displayed (first image) and resulted in the a mess of text (second image). I would suggest adding editing tools (preferably standard word tools but Markdown would be appreciated.) I would also suggest going from an aligned center (second image) to an alligned left (first image) format. It makes the text easier to read.

**Comment by alexbance** [comment]
Thanks for bringing this to mt attention, will look into adding markdown to the event(s)

**Comment by alexbance** [comment]
@josephward markdown support has been added, please re-open this if you experience any issues with it.
